package model;

import model.UserUtil;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
import org.hibernate.service.ServiceRegistry;
import org.hibernate.service.ServiceRegistryBuilder;

/**
 * HibernateUtil generated by Justin Yang
 */
public class HibernateUtil {
	
	private static final Log log = LogFactory.getLog(UserUtil.class);
	private static final SessionFactory sessionFactory = buildSessionFactory();

	private static SessionFactory buildSessionFactory() {
		try {
			// Create the SessionFactory from hibernate.cfg.xml
			Configuration configuration = new Configuration();
			configuration.configure();
			ServiceRegistry serviceRegistry = new ServiceRegistryBuilder()
					.applySettings(configuration.getProperties())
					.buildServiceRegistry();
			return configuration.buildSessionFactory(serviceRegistry);
		} catch (Throwable ex) {
			// Make sure you log the exception, as it might be swallowed
			System.err.println("Initial SessionFactory creation failed." + ex);
			throw new ExceptionInInitializerError(ex);
		}
	}

	public static SessionFactory getSessionFactory() {
		return sessionFactory;
	}

	public static void shutdown() {
		// Close caches and connection pools
		getSessionFactory().close();
	}

	public static void persist(Object transientInstance) {
		log.debug("persisting instance");
		Session session = HibernateUtil.getSessionFactory().openSession();
	    try {
	        session.beginTransaction();
	        session.save(transientInstance);
	        session.getTransaction().commit();
			log.debug("persist successful");
	    } catch (HibernateException he) {
	        session.getTransaction().rollback();
			log.error("persist failed", he);
			throw he;
	    } finally {
	        if (session != null) {
	            session.close();
	        }
	    }
	}

	public static void remove(Object persistentInstance) {
		log.debug("removing instance");
		Session session = HibernateUtil.getSessionFactory().openSession();
		try {
	        session.beginTransaction();
	        session.delete(persistentInstance);
	        session.getTransaction().commit();
			log.debug("remove successful");
		} catch (RuntimeException re) {
			log.error("remove failed", re);
			throw re;
		}
	}

	public static Object merge(Object detachedInstance) {
		log.debug("merging instance");
		Session session = HibernateUtil.getSessionFactory().openSession();
		try {
	        session.beginTransaction();
	        Object result = session.merge(detachedInstance);
	        session.getTransaction().commit();
			log.debug("merge successful");
			return result;
		} catch (RuntimeException re) {
			log.error("merge failed", re);
			throw re;
		}
	}

	@SuppressWarnings("rawtypes")
	public static Object findById(Class objectClass, int id) {
		log.debug("getting instance with id: " + id);
		Session session = HibernateUtil.getSessionFactory().openSession();
		try {
	        session.beginTransaction();
			Object instance = session.get(objectClass, id);
			log.debug("get successful");
			return instance;
		} catch (RuntimeException re) {
			log.error("get failed", re);
			throw re;
		}
	}
}